version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --requirepass mypassword  # Optional password
    volumes:
      - redis_data:/data
    environment:
      - REDIS_REPLICATION_MODE=master
    restart: always
    networks:
      - redis-network

volumes:
  redis_data:
    driver: local

networks:
  redis-network:
    driver: bridge