spring:
  application:
    name: borrowservice
  datasource:
    url: jdbc:postgresql://localhost:8386/borrowService
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:9092}
    consumer:
      group-id: borrow-group

  mail:
    host: smtp.gmail.com
    port: 587
    username: hogphat1607@gmail.com
    password: qpfmilrxltrdorhr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        transport:
          protocol: smtp

server:
  port: 9396

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

grpc:
  client:
    bookservice:
      address: localhost:6565
      keep-alive-time: 10
    employeeservice:
      address: localhost:5656
      keep-alive-time: 10